version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql_app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: graphql_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
